version: '3'
services:
  api:
    container_name: test_api
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
    environment:
      - DB_NAME=habitTest
      - DB_CONNECTION=mongodb://404bnfTest:tracker@db:27017
    depends_on:
      - db
    command: bash -c "npm install && npm run coverage"
    tty: true
  db:
    container_name: test_db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=404bnfTest
      - MONGO_INITDB_DATABASE=habitTest
      - MONGO_INITDB_ROOT_PASSWORD=tracker
    volumes:
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
      - "dbdata:/var/lib/mongodb/data"
volumes:
  dbdata:
networks:
  default:
    name: habit_api