GET http://localhost:3000/
###
GET http://localhost:3000/habits
###
GET http://localhost:3000/habits/6176870f585134fd7e4d2454
###
GET http://localhost:3000/users
###
GET http://localhost:3000/auth/
###
POST http://localhost:3000/auth/register
content-type: application/json

{
    "name": "max",
    "email": "maxxx@max.com",
    "password": "maxisthebest" 
}
###
GET http://localhost:3000/users/6176870f585134fd7e4d2454
###
POST http://localhost:3000/habits
content-type: application/json

{
    "habitName": "run",
    "userID": "6176870f585134fd7e4d2454",
    "goodHabit": true,
    "units": "km",
    "quantity": 5,  
    "days":{"mon":true, "tues":true, "wed":true, "thur":true, "fri":true, "sat":true, "sun":true}
}
###
PATCH http://localhost:3000/habits/61782c3400a32cdcce99f326



###
GET http://localhost:3000/habits/6178349929cbf635944400f7
